// web/src/components/Dashboard.svelte
<script>
  import { onMount } from 'svelte'
  import { systemStats, cameras, events } from '../stores/index.js'
  import { Activity, Camera, AlertTriangle, Clock } from 'lucide-svelte'
  import CameraCard from './CameraCard.svelte'
  import EventCard from './EventCard.svelte'

  let recentEvents = []
  let onlineCameras = []

  $: {
    // Обновляем данные при изменении stores
    recentEvents = $events.slice(0, 5)
    onlineCameras = $cameras.filter(camera => camera.status === 'online').slice(0, 4)
  }

  function formatUptime(seconds) {
    if (!seconds) return '0м'
    const hours = Math.floor(seconds / 3600)
    const minutes = Math.floor((seconds % 3600) / 60)
    if (hours > 0) {
      return `${hours}ч ${minutes}м`
    }
    return `${minutes}м`
  }

  function getStatusColor(status) {
    switch (status) {
      case 'online': return 'text-success-600 bg-success-100 border-success-200'
      case 'offline': return 'text-gray-600 bg-gray-100 border-gray-200'
      case 'error': return 'text-danger-600 bg-danger-100 border-danger-200'
      default: return 'text-gray-600 bg-gray-100 border-gray-200'
    }
  }
</script>

<div class="space-y-6">
  <!-- Page Header -->
  <div class="flex items-center justify-between">
    <h2 class="text-2xl font-bold text-gray-900 dark:text-white">
      Панель управления
    </h2>
    <div class="text-sm text-gray-500 dark:text-gray-400">
      Последнее обновление: {new Date().toLocaleTimeString('ru-RU')}
    </div>
  </div>

  <!-- Stats Grid -->
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
    <!-- Total Cameras -->
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <Camera class="h-8 w-8 text-primary-600" />
        </div>
        <div class="ml-4">
          <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Камеры</p>
          <p class="text-2xl font-semibold text-gray-900 dark:text-white">
            {$systemStats.cameras_total || 0}
          </p>
          <p class="text-xs text-success-600">
            {$systemStats.cameras_online || 0} онлайн
          </p>
        </div>
      </div>
    </div>

    <!-- Today's Events -->
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <Activity class="h-8 w-8 text-warning-600" />
        </div>
        <div class="ml-4">
          <p class="text-sm font-medium text-gray-500 dark:text-gray-400">События сегодня</p>
          <p class="text-2xl font-semibold text-gray-900 dark:text-white">
            {$systemStats.events_today || 0}
          </p>
          <p class="text-xs text-gray-600 dark:text-gray-400">
            За последние 24ч
          </p>
        </div>
      </div>
    </div>

    <!-- Total Events -->
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <AlertTriangle class="h-8 w-8 text-danger-600" />
        </div>
        <div class="ml-4">
          <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Всего событий</p>
          <p class="text-2xl font-semibold text-gray-900 dark:text-white">
            {$systemStats.events_total || 0}
          </p>
          <p class="text-xs text-gray-600 dark:text-gray-400">
            За все время
          </p>
        </div>
      </div>
    </div>

    <!-- System Uptime -->
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <Clock class="h-8 w-8 text-success-600" />
        </div>
        <div class="ml-4">
          <p class="text-sm font-medium text-gray-500 dark:text-gray-400">Время работы</p>
          <p class="text-2xl font-semibold text-gray-900 dark:text-white">
            {formatUptime($systemStats.system_uptime)}
          </p>
          <p class="text-xs text-success-600">
            Система стабильна
          </p>
        </div>
      </div>
    </div>
  </div>

  <!-- Two Column Layout -->
  <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
    <!-- Active Cameras -->
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
      <div class="p-6 border-b border-gray-200 dark:border-gray-700">
        <div class="flex items-center justify-between">
          <h3 class="text-lg font-medium text-gray-900 dark:text-white">
            Активные камеры
          </h3>
          <span class="text-sm text-gray-500 dark:text-gray-400">
            {onlineCameras.length} из {$cameras.length}
          </span>
        </div>
      </div>
      <div class="p-6">
        {#if onlineCameras.length > 0}
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {#each onlineCameras as camera (camera.id)}
              <CameraCard {camera} showControls={false} />
            {/each}
          </div>
          {#if $cameras.length > 4}
            <div class="mt-4 text-center">
              <button 
                class="text-primary-600 hover:text-primary-700 dark:text-primary-400 dark:hover:text-primary-300 text-sm font-medium"
                on:click={() => window.dispatchEvent(new CustomEvent('navigate', { detail: 'cameras' }))}
              >
                Показать все камеры ({$cameras.length})
              </button>
            </div>
          {/if}
        {:else}
          <div class="text-center py-8">
            <Camera class="mx-auto h-12 w-12 text-gray-400" />
            <h3 class="mt-2 text-sm font-medium text-gray-900 dark:text-white">
              Нет активных камер
            </h3>
            <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
              Добавьте камеру для начала мониторинга
            </p>
            <div class="mt-6">
              <button 
                class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500"
                on:click={() => window.dispatchEvent(new CustomEvent('navigate', { detail: 'cameras' }))}
              >
                <Camera class="-ml-1 mr-2 h-5 w-5" />
                Добавить камеру
              </button>
            </div>
          </div>
        {/if}
      </div>
    </div>

    <!-- Recent Events -->
    <div class="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
      <div class="p-6 border-b border-gray-200 dark:border-gray-700">
        <div class="flex items-center justify-between">
          <h3 class="text-lg font-medium text-gray-900 dark:text-white">
            Последние события
          </h3>
          <span class="text-sm text-gray-500 dark:text-gray-400">
            Топ 5
          </span>
        </div>
      </div>
      <div class="p-6">
        {#if recentEvents.length > 0}
          <div class="space-y-4">
            {#each recentEvents as event (event.id)}
              <EventCard {event} compact={true} />
            {/each}
          </div>
          <div class="mt-4 text-center">
            <button 
              class="text-primary-600 hover:text-primary-700 dark:text-primary-400 dark:hover:text-primary-300 text-sm font-medium"
              on:click={() => window.dispatchEvent(new CustomEvent('navigate', { detail: 'events' }))}
            >
              Показать все события
            </button>
          </div>
        {:else}
          <div class="text-center py-8">
            <Activity class="mx-auto h-12 w-12 text-gray-400" />
            <h3 class="mt-2 text-sm font-medium text-gray-900 dark:text-white">
              Нет событий
            </h3>
            <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">
              События будут отображаться здесь после обнаружения
            </p>
          </div>
        {/if}
      </div>
    </div>
  </div>
</div>

// web/app/(app)/dashboard/page.tsx
'use client';

import { useEffect } from 'react';
import { Camera, Activity, AlertTriangle, Clock } from 'lucide-react';
import { useAppStore } from '@/stores/app';

export default function DashboardPage() {
  const { 
    systemStats, 
    cameras, 
    events,
    currentTime,
    loadCameras,
    loadEvents,
    loadStats
  } = useAppStore();

  useEffect(() => {
    // Load initial data
    loadCameras();
    loadEvents({ limit: 5 });
    loadStats();

    // Refresh data every 30 seconds
    const interval = setInterval(() => {
      loadStats();
    }, 30000);

    return () => clearInterval(interval);
  }, [loadCameras, loadEvents, loadStats]);

  const formatUptime = (seconds: number) => {
    if (!seconds) return '0m';
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    if (hours > 0) {
      return `${hours}h ${minutes}m`;
    }
    return `${minutes}m`;
  };

  const onlineCameras = cameras.filter(cam => cam.status === 'online');
  const recentEvents = events.slice(0, 5);

  return (
    <div className="p-6 space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
          Dashboard
        </h2>
        <div className="text-sm text-gray-500 dark:text-gray-400">
          Last update: {currentTime}
        </div>
      </div>

      {/* Live Data Indicator */}
      <div className="flex items-center space-x-2 text-sm text-gray-500">
        <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
        <span>Live data updates every 5 seconds</span>
        <span className="text-xs">({currentTime})</span>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {/* Total Cameras */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
          <div className="flex items-center">
            <div className="flex-shrink-0">
              <Camera className="h-8 w-8 text-blue-600" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-500 dark:text-gray-400">Cameras</p>
              <p className="text-2xl font-semibold text-gray-900 dark:text-white">
                {systemStats.cameras_total || 0}
              </p>
              <p className="text-xs text-green-600">
                {systemStats.cameras_online || 0} online
              </p>
            </div>
          </div>
        </div>

        {/* Today's Events */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
          <div className="flex items-center">
            <div className="flex-shrink-0">
              <Activity className="h-8 w-8 text-yellow-600" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-500 dark:text-gray-400">Events Today</p>
              <p className="text-2xl font-semibold text-gray-900 dark:text-white">
                {systemStats.events_today || 0}
              </p>
              <p className="text-xs text-gray-600 dark:text-gray-400">
                Last 24 hours
              </p>
            </div>
          </div>
        </div>

        {/* Total Events */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
          <div className="flex items-center">
            <div className="flex-shrink-0">
              <AlertTriangle className="h-8 w-8 text-red-600" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-500 dark:text-gray-400">Total Events</p>
              <p className="text-2xl font-semibold text-gray-900 dark:text-white">
                {systemStats.events_total || 0}
              </p>
              <p className="text-xs text-gray-600 dark:text-gray-400">
                All time
              </p>
            </div>
          </div>
        </div>

        {/* System Uptime */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6">
          <div className="flex items-center">
            <div className="flex-shrink-0">
              <Clock className="h-8 w-8 text-green-600" />
            </div>
            <div className="ml-4">
              <p className="text-sm font-medium text-gray-500 dark:text-gray-400">Uptime</p>
              <p className="text-2xl font-semibold text-gray-900 dark:text-white">
                {formatUptime(systemStats.system_uptime)}
              </p>
              <p className="text-xs text-green-600">
                System stable
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Two Column Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Active Cameras */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
          <div className="p-6 border-b border-gray-200 dark:border-gray-700">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-medium text-gray-900 dark:text-white">
                Active Cameras
              </h3>
              <span className="text-sm text-gray-500 dark:text-gray-400">
                {onlineCameras.length} of {cameras.length}
              </span>
            </div>
          </div>
          <div className="p-6">
            {onlineCameras.length > 0 ? (
              <div className="space-y-4">
                {onlineCameras.slice(0, 4).map((camera) => (
                  <div key={camera.id} className="flex items-center justify-between p-4 bg-gray-50 dark:bg-gray-700 rounded-lg">
                    <div className="flex items-center space-x-3">
                      <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                      <div>
                        <p className="text-sm font-medium text-gray-900 dark:text-white">{camera.name}</p>
                        <p className="text-xs text-gray-500 dark:text-gray-400">ID: {camera.id}</p>
                      </div>
                    </div>
                    <span className="text-xs text-green-600 dark:text-green-400">Online</span>
                  </div>
                ))}
                {cameras.length > 4 && (
                  <a href="/cameras" className="block text-center text-sm text-blue-600 hover:text-blue-700">
                    View all cameras ({cameras.length})
                  </a>
                )}
              </div>
            ) : (
              <div className="text-center py-8">
                <Camera className="mx-auto h-12 w-12 text-gray-400" />
                <h3 className="mt-2 text-sm font-medium text-gray-900 dark:text-white">
                  No active cameras
                </h3>
                <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  Add a camera to start monitoring
                </p>
                <div className="mt-6">
                  <a
                    href="/cameras"
                    className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700"
                  >
                    <Camera className="-ml-1 mr-2 h-5 w-5" />
                    Add Camera
                  </a>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Recent Events */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700">
          <div className="p-6 border-b border-gray-200 dark:border-gray-700">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-medium text-gray-900 dark:text-white">
                Recent Events
              </h3>
              <span className="text-sm text-gray-500 dark:text-gray-400">
                Latest 5
              </span>
            </div>
          </div>
          <div className="p-6">
            {recentEvents.length > 0 ? (
              <div className="space-y-4">
                {recentEvents.map((event) => (
                  <div key={event.id} className="flex items-start space-x-3 p-4 bg-gray-50 dark:bg-gray-700 rounded-lg">
                    <div className={`flex-shrink-0 w-2 h-2 rounded-full mt-1.5 ${
                      event.type === 'motion' ? 'bg-yellow-500' : 'bg-blue-500'
                    }`} />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-gray-900 dark:text-white">
                        {event.camera_name}
                      </p>
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        {event.type === 'motion' ? 'Motion detected' : `AI: ${event.object_class}`}
                      </p>
                      <p className="text-xs text-gray-400 dark:text-gray-500 mt-1">
                        {new Date(event.created_at).toLocaleString()}
                      </p>
                    </div>
                  </div>
                ))}
                <a href="/events" className="block text-center text-sm text-blue-600 hover:text-blue-700">
                  View all events
                </a>
              </div>
            ) : (
              <div className="text-center py-8">
                <Activity className="mx-auto h-12 w-12 text-gray-400" />
                <h3 className="mt-2 text-sm font-medium text-gray-900 dark:text-white">
                  No events
                </h3>
                <p className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  Events will appear here when detected
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
