// web/components/layout/Sidebar.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Home, Camera, Activity, Settings, X } from 'lucide-react';

interface SidebarProps {
  isOpen: boolean;
  onClose: () => void;
}

const navItems = [
  { href: '/dashboard', label: 'Dashboard', icon: Home },
  { href: '/cameras', label: 'Cameras', icon: Camera },
  { href: '/events', label: 'Events', icon: Activity },
  { href: '/settings', label: 'Settings', icon: Settings },
];

export function Sidebar({ isOpen, onClose }: SidebarProps) {
  const pathname = usePathname();

  return (
    <>
      {/* Mobile sidebar backdrop */}
      {isOpen && (
        <div 
          className="fixed inset-0 z-40 bg-gray-600 bg-opacity-75 lg:hidden"
          onClick={onClose}
        />
      )}

      {/* Sidebar */}
      <div className={`
        fixed inset-y-0 left-0 z-50 w-64 bg-white dark:bg-gray-800 transform transition-transform duration-300 ease-in-out lg:translate-x-0 lg:static lg:inset-0
        ${isOpen ? 'translate-x-0' : '-translate-x-full'}
      `}>
        <div className="flex items-center justify-between h-16 px-6 border-b border-gray-200 dark:border-gray-700">
          <div className="flex items-center space-x-3">
            <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center">
              <svg className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
              </svg>
            </div>
            <span className="text-xl font-semibold text-gray-900 dark:text-white">Ocuai</span>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 dark:hover:bg-gray-700 lg:hidden"
          >
            <X size={20} />
          </button>
        </div>

        <nav className="mt-5 px-3">
          <div className="space-y-1">
            {navItems.map((item) => {
              const Icon = item.icon;
              const isActive = pathname === item.href;
              
              return (
                <Link
                  key={item.href}
                  href={item.href}
                  onClick={() => onClose()}
                  className={`
                    group flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors
                    ${isActive
                      ? 'bg-indigo-100 dark:bg-indigo-900/20 text-indigo-700 dark:text-indigo-300'
                      : 'text-gray-700 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white hover:bg-gray-50 dark:hover:bg-gray-700'
                    }
                  `}
                >
                  <Icon 
                    className={`
                      mr-3 h-5 w-5 flex-shrink-0
                      ${isActive
                        ? 'text-indigo-600 dark:text-indigo-400'
                        : 'text-gray-400 dark:text-gray-500 group-hover:text-gray-500 dark:group-hover:text-gray-400'
                      }
                    `}
                  />
                  {item.label}
                </Link>
              );
            })}
          </div>
        </nav>

        {/* Bottom section */}
        <div className="absolute bottom-0 left-0 right-0 p-4 border-t border-gray-200 dark:border-gray-700">
          <div className="flex items-center space-x-3 px-3 py-2 text-sm text-gray-600 dark:text-gray-400">
            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
            <span>System Online</span>
          </div>
        </div>
      </div>
    </>
  );
}

// web/src/components/Sidebar.svelte
<script>
  import { createEventDispatcher } from 'svelte'
  import { Home, Camera, Activity, Settings, X } from 'lucide-svelte'

  export let currentPage = 'dashboard'
  export let sidebarOpen = false

  const dispatch = createEventDispatcher()

  const menuItems = [
    { id: 'dashboard', label: 'Панель', icon: Home },
    { id: 'cameras', label: 'Камеры', icon: Camera },
    { id: 'events', label: 'События', icon: Activity },
    { id: 'settings', label: 'Настройки', icon: Settings }
  ]

  function navigate(page) {
    dispatch('navigate', page)
  }

  function closeSidebar() {
    dispatch('toggle')
  }
</script>

<!-- Mobile backdrop -->
{#if sidebarOpen}
  <div 
    class="fixed inset-0 bg-black bg-opacity-50 z-40 lg:hidden"
    on:click={closeSidebar}
    role="button"
    tabindex="0"
    on:keydown={() => {}}
  ></div>
{/if}

<!-- Sidebar -->
<div class="fixed inset-y-0 left-0 z-50 w-64 bg-white dark:bg-gray-800 shadow-lg
            transform transition-transform duration-300 ease-in-out lg:translate-x-0 lg:static lg:inset-0
            {sidebarOpen ? 'translate-x-0' : '-translate-x-full'}">
  
  <!-- Sidebar header -->
  <div class="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
    <div class="flex items-center space-x-3">
      <div class="w-8 h-8 bg-primary-500 rounded-lg flex items-center justify-center">
        <Camera size={20} class="text-white" />
      </div>
      <span class="text-xl font-bold text-gray-900 dark:text-white">Ocuai</span>
    </div>
    
    <!-- Close button (mobile only) -->
    <button
      on:click={closeSidebar}
      class="p-2 rounded-md text-gray-500 hover:text-gray-900 hover:bg-gray-100 
             dark:text-gray-400 dark:hover:text-white dark:hover:bg-gray-700 
             lg:hidden"
    >
      <X size={20} />
    </button>
  </div>

  <!-- Navigation -->
  <nav class="mt-6 px-3">
    <ul class="space-y-2">
      {#each menuItems as item (item.id)}
        <li>
          <button
            on:click={() => navigate(item.id)}
            class="w-full flex items-center px-3 py-2 text-sm font-medium rounded-lg
                   transition-colors duration-200 group
                   {currentPage === item.id 
                     ? 'bg-primary-100 text-primary-700 dark:bg-primary-900 dark:text-primary-300' 
                     : 'text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-700'}"
          >
            <svelte:component 
              this={item.icon} 
              size={20} 
              class="mr-3 flex-shrink-0 {currentPage === item.id 
                      ? 'text-primary-600 dark:text-primary-400' 
                      : 'text-gray-400 group-hover:text-gray-500 dark:text-gray-500 dark:group-hover:text-gray-400'}" 
            />
            {item.label}
          </button>
        </li>
      {/each}
    </ul>
  </nav>

  <!-- Sidebar footer -->
  <div class="absolute bottom-0 left-0 right-0 p-6 border-t border-gray-200 dark:border-gray-700">
    <div class="flex items-center space-x-3">
      <div class="w-8 h-8 bg-gray-300 dark:bg-gray-600 rounded-full flex items-center justify-center">
        <span class="text-xs font-medium text-gray-700 dark:text-gray-300">AI</span>
      </div>
      <div>
        <p class="text-sm font-medium text-gray-900 dark:text-white">
          Система активна
        </p>
        <p class="text-xs text-gray-500 dark:text-gray-400">
          Версия 1.0.0
        </p>
      </div>
    </div>
  </div>
</div>
